name: action1
on: [push]

jobs:
  run-shell:
    runs-on: ubuntu-latest
    needs: run-maci
    steps:
      - name: echo string
        run: echo 'hello world'
  
  run-windows:
    runs-on: windows-latest
    steps:
      - name: echo running window
        run: echo 'window second job'
  run-maci:
    runs-on: macos-latest
    steps:
      - name: echo running window
        run: echo 'window second job'
