name: Workflow with User Inputs
 
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
        default: 'John Doe'
      environment:
        description: 'Choose the environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      deploy:
        description: 'Deploy the application'
        required: true
        default: 'no'
        type: boolean
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Display input values
        run: |
          echo "Hello, ${{ github.event.inputs.name }}"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Deploy: ${{ github.event.inputs.deploy }}"
 
      - name: Conditionally deploy
        if: ${{ github.event.inputs.deploy == 'true' }}
        run: echo "Deploying to ${{ github.event.inputs.environment }} environment!"
