name : shell and directory
on : [push]
defaults:
    run:
        shell : bash
jobs:
    git_clone_job:
        runs-on : ubuntu-latest
        steps:
            - name : execute git commands
              run : ls -a 
            - name : printing git variables
              run : |
                echo $GITHUB_ACTOR
                echo $GITHUB_REPOSITORY
                echo ${{ secrets.GIT_HUB_TOKEN }}
            - name : clonerepo
              run : |
                git init
                git config --global user.name "gowtham9610"
                git config --global user.email "gowtham9610@gmail.com"
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GIT_HUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main 
                ls -a

