name : shell and directory
on : [push]
defaults:
    run:
        shell : bash
jobs:
    git_clone_job:
        runs-on : ubuntu-latest
        steps:
            - name : execute git commands
              run : ls -a 
            - name : printing git variables
              run : |
                echo $GITHUB_ACTOR
                echo $GITHUB_REPOSITORY
                echo ${{ secrets.GIT_HUB_TOKEN }}