name : using methods
on : [push]

jobs :
    for_checkout:
      runs-on : ubuntu-latest
      steps :
        - name : before_checkout
          run: ls -a
        - name : cloning_git
          uses: actions/checkout@v4
        - name : after_checkout
          run: |
            ls -a
            cat README.md

